/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        dm: ['DM Sans', 'sans-serif'],
      },
      colors: {
        or:  '#FF7A00',
        or2: '#FF9A3C',
        or3: '#E06000',
        cr:  '#FEF6E4',
        yw:  '#FFD54F',
        yw2: '#F9A825',
        br:  '#5D4037',
        br2: '#8D6E63',
        gn:  '#43A047',
        gn2: '#E8F5E9',
        gn3: '#2E7D32',
        rd:  '#E53935',
        rd2: '#FFEBEE',
        bl:  '#1E88E5',
        bl2: '#E3F2FD',
        // Premium SaaS Palette
        premium: {
          orange: '#FF6B00',
          orangeLight: '#FF8C00',
          orangePale: '#FFB347',
          cream: '#FFF7E8',
          creamDark: '#FFF3E0',
          white: '#FFFFFF',
          gray50: '#F8F9FA',
          gray200: '#E5E7EB',
          gray700: '#374151',
          gray900: '#111827',
        }
      },
      keyframes: {
        fadeUp:    { from: { opacity: 0, transform: 'translateY(20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        fadeIn:    { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp:   { from: { transform: 'translateY(100%)', opacity: 0 }, to: { transform: 'translateY(0)', opacity: 1 } },
        zoomIn:    { from: { transform: 'scale(.85)', opacity: 0 }, to: { transform: 'scale(1)', opacity: 1 } },
        bounceIn:  { '0%': { transform: 'scale(.3)', opacity: 0 }, '55%': { transform: 'scale(1.07)' }, '75%': { transform: 'scale(.95)' }, '100%': { transform: 'scale(1)', opacity: 1 } },
        pulse2:    { '0%,100%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.04)' } },
        float:     { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        floatSlow: { 
          '0%, 100%': { transform: 'translate(0, 0)' },
          '33%': { transform: 'translate(20px, -30px)' },
          '66%': { transform: 'translate(-15px, 15px)' },
        },
        spin2:     { to: { transform: 'rotate(360deg)' } },
        shimmer:   { '0%': { backgroundPosition: '-400px 0' }, '100%': { backgroundPosition: '400px 0' } },
        dotBounce: { '0%,80%,100%': { transform: 'translateY(0)' }, '40%': { transform: 'translateY(-9px)' } },
        toastIn:   { from: { opacity: 0, transform: 'translate(-50%,16px)' }, to: { opacity: 1, transform: 'translate(-50%,0)' } },
        stampPop:  { '0%': { transform: 'scale(0) rotate(-20deg)', opacity: 0 }, '70%': { transform: 'scale(1.2)' }, '100%': { transform: 'scale(1)', opacity: 1 } },
        confetti:  { '0%': { transform: 'translateY(0) rotate(0)', opacity: 1 }, '100%': { transform: 'translateY(120px) rotate(720deg)', opacity: 0 } },
        cashSpin:  { '0%,100%': { transform: 'rotate(-8deg)' }, '50%': { transform: 'rotate(8deg)' } },
        trackPulse:{ '0%,100%': { boxShadow: '0 0 0 0 rgba(67,160,71,.4)' }, '70%': { boxShadow: '0 0 0 8px rgba(67,160,71,0)' } },
      },
      animation: {
        fadeUp:     'fadeUp .3s ease both',
        fadeIn:     'fadeIn .3s ease',
        slideUp:    'slideUp .32s ease',
        zoomIn:     'zoomIn .28s ease',
        bounceIn:   'bounceIn .5s ease',
        float:      'float 3.5s ease-in-out infinite',
        floatSlow:  'floatSlow 8s ease-in-out infinite',
        shimmer:    'shimmer 1.6s infinite',
        dotBounce:  'dotBounce 1.4s ease-in-out infinite',
        toastIn:    'toastIn .3s ease',
        stampPop:   'stampPop .4s ease',
        pulse2:     'pulse2 1.5s ease-in-out infinite',
        cashSpin:   'cashSpin 2s ease-in-out infinite',
        trackPulse: 'trackPulse 1.5s ease-out',
        confetti:   'confetti 1.2s ease forwards',
      },
      boxShadow: {
        sh1: '0 2px 10px rgba(93,64,55,.08)',
        sh2: '0 6px 24px rgba(93,64,55,.14)',
        sh3: '0 12px 48px rgba(93,64,55,.2)',
        or:  '0 6px 24px rgba(255,122,0,.4)',
      },
    },
  },
  plugins: [],
}
